package ca.corbett.imageviewer.extensions.stegpng;

/**
 * This class stores information about a stegged image - namely,
 * how many bytes of secret message data it contains, and what
 * data compaction level was used to store it.
 * <p>
 * Instances of this class are immutable.
 * </p>
 *
 * @author <a href="https://github.com/scorbo2">scorbo2</a>
 * @since 2004-10-17 originally! But not updated for over two decades, until 2026-03-14.
 */
public class StegInfo {

    private final byte majorVersion;
    private final byte minorVersion;
    private final int dataSegmentLength;
    private final byte dataCompactionLevel;
    private final PayloadType payloadType;

    /**
     * Indicates how many bytes a StegInfo class will occupy
     * when written as a header to a stegged image.
     * <p>
     * <b>Implementation note:</b> internally, the header consists
     * of the following:
     * </p>
     * <ul>
     * <li>2 bytes - A StegPNG "magic number" for identification purposes.
     * <li>2 bytes - version information (major, minor)
     * <li>1 byte - data compaction level (1 - 8)
     * <li>1 byte - message type (one of the PayloadType values)
     * <li>4 bytes - data segment length
     * </ul>
     */
    public static final int HEADER_SIZE = 10;

    /** Used to identify a stegged image as being generated by StegPNG. */
    public static final short MAGIC_NUMBER = (short)0x5350; // "SP" in ASCII


    /**
     * Creates a StegInfo instance with the specified parameters.
     *
     * @param compactionLevel The desired compaction level, from 1 to 8.
     * @param payloadType     a PayloadType constant indicating the type of data being embedded (string or binary).
     * @param messageLength   The length of the data segment, in bytes.
     */
    public StegInfo(byte compactionLevel, PayloadType payloadType, int messageLength) {
        if (compactionLevel < 1 || compactionLevel > 8) {
            throw new IllegalArgumentException("Compaction level must be between 1 and 8.");
        }
        if (payloadType == null) {
            throw new IllegalArgumentException("Payload type cannot be null.");
        }
        majorVersion = StegPNG.MAJOR_VERSION;
        minorVersion = StegPNG.MINOR_VERSION;
        dataCompactionLevel = compactionLevel;
        this.payloadType = payloadType;
        dataSegmentLength = messageLength;
    }


    /**
     * Creates a new instance using the data in the specified byte array.
     * This constructor is used by the StegPng class itself and should
     * probably never need to be called by a client application.
     *
     * @param data A byte array representing the raw data for this instance.
     * @throws InvalidPayloadException If the given header doesn't appear valid.
     * @throws InvalidVersionException If the version information in the header is not recognized.
     */
    public StegInfo(byte[] data) throws InvalidPayloadException, InvalidVersionException {
        if (data == null || data.length < HEADER_SIZE) {
            throw new IllegalArgumentException("Data array must be at least " + HEADER_SIZE + " bytes long.");
        }

        // Reassemble the magic number from the first two bytes:
        short magic = (short)(((data[0] << 8) & 0xFF00) | (data[1] & 0xFF));
        if (magic != MAGIC_NUMBER) {
            throw new InvalidPayloadException();
        }

        // Assemble the version and make sure it matches:
        majorVersion = data[2];
        minorVersion = data[3];

        // This is perhaps a bit strict, but we will reject any version
        // that doesn't exactly match our current version.
        if (majorVersion != StegPNG.MAJOR_VERSION || minorVersion != StegPNG.MINOR_VERSION) {
            throw new InvalidVersionException();
        }

        // Data compaction level and message type must also be correct:
        dataCompactionLevel = data[4];
        PayloadType messageType = PayloadType.ofValue(data[5]);
        if (dataCompactionLevel < 1 || dataCompactionLevel > 8 || messageType == null) {
            throw new InvalidPayloadException(); // generic "this ain't no StegPNG message" exception
        }
        payloadType = messageType;

        // Finally, get the length of the data segment:
        // (convert the last four header bytes back into a 32 bit int):
        dataSegmentLength = ((data[6] << 24) & 0xFF000000) |
                ((data[7] << 16) & 0xFF0000) |
                ((data[8] << 8) & 0xFF00) |
                (data[9] & 0xFF);
        if (dataSegmentLength <= 0) {
            throw new InvalidPayloadException(); // generic "this ain't no StegPNG message" exception
        }
    }


    /**
     * Constructs and returns a byte array from the internal properties
     * of this class.
     *
     * @return A byte array representing the properties of this instance.
     */
    public byte[] toByteArray() {
        byte[] data = new byte[HEADER_SIZE];

        // Embed the magic number:
        data[0] = (byte)((MAGIC_NUMBER >> 8) & 0xFF);
        data[1] = (byte)(MAGIC_NUMBER & 0xFF);

        // Embed version information:
        data[2] = StegPNG.MAJOR_VERSION;
        data[3] = StegPNG.MINOR_VERSION;

        // Data compaction level:
        data[4] = dataCompactionLevel;

        // Embed message type:
        data[5] = payloadType.getValue();

        // Embed length of data portion:
        // (convert the 32 bit int to four separate bytes):
        data[6] = (byte)((dataSegmentLength >> 24) & 0xFF);
        data[7] = (byte)((dataSegmentLength >> 16) & 0xFF);
        data[8] = (byte)((dataSegmentLength >> 8) & 0xFF);
        data[9] = (byte)(dataSegmentLength & 0xFF);

        return data;
    }

    /**
     * Returns the major version of StegPNG that was used to embed the message.
     */
    public byte getMajorVersion() {
        return majorVersion;
    }

    /**
     * Returns the minor version of StegPNG that was used to embed the message.
     */
    public byte getMinorVersion() {
        return minorVersion;
    }

    /**
     * Returns the length of the data segment (this is the length,
     * in bytes, of the secret message). Note: we use a 32 bit int
     * instead of a 64 bit long, only because it's very unlikely that
     * a PNG image would be large enough to hold a message larger
     * than 2GB.
     *
     * @return The length, in bytes, of the data segment (secret message).
     */
    public int getDataSegmentLength() {
        return dataSegmentLength;
    }

    /**
     * Returns the PayloadType associated with this message.
     */
    public PayloadType getPayloadType() {
        return payloadType;
    }

    /**
     * Returns the data compaction level of the secret message.
     * This is the number of bits per byte that the secret
     * message occupies in the container image.  The values
     * range from 1 (low compression, minimum effect on quality
     * of container image) to 8 (high compression, total destruction
     * of container image data).
     *
     * @return The current data compaction level, from 1 to 8.
     */
    public byte getDataCompactionLevel() {
        return dataCompactionLevel;
    }
}

